### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by dnltsk** [dcarral/good-code#1]
Hi @dcarral ,
on the swk Meetup Mo 18th Dec you asked us to to a pull request on your repo but I have no clue how this could look like. I think we do not want to pull a solution to into the kata. So I tend to create a language specific branch. How do you think about that?
Cheers and kind regards,
Daniel

**Comment by dcarral** [comment]
Hey, awesome to read you Daniel :-) 

If I remember correctly, yesterday I was inviting to contribute with improvements to the initial test suites / project setups (@ https://github.com/dcarral/99bottles-polyglot). I've just seen 2 open PRs there, so cool! Thanks a lot!

Regarding the language-specific solutions, it's an excellent point. I've just set up https://github.com/dcarral/99bottles-solutions, where we could easily open PRs with our solutions (structure-wise: a directory per language, containing wrapper directories named after our GitHub usernames). 

What do you think?

**Comment by dnltsk** [comment]
👍  
only disadvantage is that test suite and solutions are decoupled which will leads to inconsistency when the test suite is getting fixed or adjusted. But for the first throw it's an absolutely valid way.

Cheers.

**Comment by dcarral** [comment]
Cool, thank you very much for your contributions Daniel! 

Now that we have sorted it out, let's close the issue ;)
